library(Seurat)
setwd("~/BINF/yushi scrnaseq/E9.5/Pax3/ref_annot")
cc <- readRDS("~/BINF/yushi scrnaseq/E9.5/Pax3/ref_annot/pax95.rds")
cc<- FindClusters(cc, resolution = 0.6)
DimPlot(cc, reduction = "umap", label = TRUE, label.size = 5)
saveRDS(cc, "pax3E9.5_resolution_0.6.rds")
